version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      GitHub_Actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
